### ISSUE TITLE
SSH connection breaks when activating HQ Camera for Raspiraw

### ISSUE THREAD

**Issue by alivedoom** [raspberrypi/raspiraw#38]
I can use raspiraw flawlessly directly on the rasperrypi.  But if i have it connected to a windows pc through ethernet creating an SSH and run camera_i2c my SSH connection breaks while on ethernet but it doesnt happen when on wireless connection. Any clue why that happens? PS I'm using the HQ Camera & Raspberry Pi 4

**Comment by 6by9** [comment]
camera_i2c is incorrect for Pi4 as it resets the pinmuxing of GPIOs 28&29 when it shouldn't.

**Comment by 6by9** [comment]
camera_i2c updated so it doesn't modify GPIOs 28&29 on Pi4.

**Comment by alivedoom** [comment]
Thank you! In the meantime i hooked it up to an usb-ethernet adapter but ill switch back to the built in.

**Comment by 6by9** [comment]
Closing as resolved.
