### ISSUE TITLE
Raspiraw reaches 'No AWB' but does not finish command (Raspberry Pi 4 B, IMX477)

### ISSUE THREAD

**Issue by Emmett-Dec** [raspberrypi/raspiraw#50]
I am running buster and my setup includes a Pi 4 model B and the HQ camera sensor.
![image](https://user-images.githubusercontent.com/70596009/108409384-29ab8e80-71f4-11eb-8e2c-0979ea9460b1.png)

**Comment by rolly-ng** [comment]
-y 10 means that you are calling i2c address 10, whereas raspiraw found your camera on i2c-1a?

**Comment by 6by9** [comment]
> -y 10 means that you are calling i2c address 10, whereas raspiraw found your camera on i2c-1a?

No, -y 10 means use /dev/i2c-10 to look for sensors as you can see from the following line
"Using I2C device /dev/i2c-10"
This is correct for any 5.4 or later Pi kernel.
Each sensor has a hard coded address at which a specific register is checked to see if it matches the hard coded "signature" for that sensor.

@Emmett-Dec does this HQ camera work OK with raspistill/vid? Do modes other than -md 3 work?

**Comment by Emmett-Dec** [comment]
Yes, raspistill/vid work perfectly with the HQ cam.

Just ran the same command this morning after restarting my Pi (with -md 3) and the command finished but the .raw was empty
![image](https://user-images.githubusercontent.com/70596009/108600246-1f100700-7364-11eb-97f1-17d701e7d332.png)
![image](https://user-images.githubusercontent.com/70596009/108600252-2df6b980-7364-11eb-8f5b-a872135b78a7.png)

Switching to mode 2 worked and resulted in a 3.2 MB .raw file
Mode 1 worked and resulted in a 4.56 MB .raw file
Mode 0 resulted in this error:
![image](https://user-images.githubusercontent.com/70596009/108600369-ede40680-7364-11eb-8211-52c0916cde8c.png)

**Comment by rolly-ng** [comment]
Thanks to 6by9 for the correction. Plz try to increase your GPU memory to 256MB at least.

**Comment by Emmett-Dec** [comment]
`uname -a` shows
`Linux GillesPi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux`

I've set GPU memory to 512 as suggested

This is what my GPIO looks like when running `camera_i2c` before restarting
![image](https://user-images.githubusercontent.com/70596009/108633304-95366b80-7441-11eb-996a-a523eca72ef4.png)

I then reset my Pi and `camera_i2c` did the following:
![image](https://user-images.githubusercontent.com/70596009/108633773-1e4ea200-7444-11eb-974c-d9116558bdf1.png)

I've noticed that raspiraw seems to work for my setup when a:10 is empty and 4:60 is set to 64, but `camera_i2c` sets the GPIO to either of those two states. Can anyone comment on this?

**Comment by 6by9** [comment]
The power to the camera module (on address 0x1a) is controlled via a GPIO.
The firmware camera driver (ie raspistill/vid) will set and clear that GPIO as the camera is used.
camera_i2c will set the GPIO to enable the camera, and it will be left enabled, hence address 0x1a responding via i2cdetect.

The result of the i2cdetect from within camera_i2c means relatively little - the sensor takes about 250ms to power up fully after power is applied, and camera_i2c doesn't wait at all before probing.

**Comment by rolly-ng** [comment]
> `uname -a` shows
> `Linux GillesPi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux`
> 
> I've set GPU memory to 512 as suggested
> 
> This is what my GPIO looks like when running `camera_i2c` before restarting
> ![image](https://user-images.githubusercontent.com/70596009/108633304-95366b80-7441-11eb-996a-a523eca72ef4.png)
> 
> I then reset my Pi and `camera_i2c` did the following:
> ![image](https://user-images.githubusercontent.com/70596009/108633773-1e4ea200-7444-11eb-974c-d9116558bdf1.png)
> 
> I've noticed that raspiraw seems to work for my setup when a:10 is empty and 4:60 is set to 64, but `camera_i2c` sets the GPIO to either of those two states. Can anyone comment on this?

I am have board revision d03114 and I usually repeat ./camera_i2c 1a twice to have the a10 showing 1a before running raspiraw. It works fine so far.

**Comment by Emmett-Dec** [comment]
The increase in memory seems to have fixed the earlier issue. I am now getting issues with all data being written to a single .raw file when using `./raspiraw -md 2 -t 1000 -ts /dev/shm/tstamps.csv -hd0 /dev/shm/hd0.32k --fps 660 -sr 1 -o /dev/shm/out.%06d.raw`
I am having the same issue when lowering fps to 350.
![image](https://user-images.githubusercontent.com/70596009/109196130-52d69c80-7769-11eb-8f86-65a1f6f7f1a0.png)
