### ISSUE TITLE
--top not working on IMX129 (raspberry 3 B+, IMX129) 

### ISSUE THREAD

**Issue by Inkomidwastaken** [raspberrypi/raspiraw#51]
Using the ```--top``` command line option with the IMX219 is resulting in:
```RaspiRaw: This sensor does not currently support manual cropping settings. Aborting```

So, is this supposed to be not working? ```--width``` and ```--height``` are working fine.
Is there any other way to capture lines in the middle of the sensor without captureng the lines above?

**Comment by 6by9** [comment]
Arbitrary cropping has to be implemented on a per sensor basis, and that has only been done for OV5647.
May be solved by #54

**Comment by ruzko** [comment]
I don't mean to necro-bump, but is manual cropping necessary to record high fps on IMX219?
