### ISSUE TITLE
Issues on Zero 2 W

### ISSUE THREAD

**Issue by VisoFIH** [raspberrypi/raspiraw#64]
Hi!
I'm having some trouble getting raspiraw working on a zero 2 W.
I've looked around a bit, and it appears that it is not supported yet? -Or am I mistaken?
I'm getting the "Failed: don't know how to set GPIO for this board!" error when running camera_i2c

**Comment by 6by9** [comment]
Should be fixed by https://github.com/raspberrypi/raspiraw/commit/c927d0e1d7a8503324a6808c0e5ede756715fd1d
